# -*- coding: utf-8 -*-
"""test_pygame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1194BL5JYU3oCSyQVFBwLCG3Hpdy0G48r
"""
import sys
print(sys.executable)
try:
    import pygame
    print(pygame.ver)
    print("Pygame imported successfully!")
except ModuleNotFoundError:
    print("Pygame import failed!")